# Generated by Django 4.0 on 2021-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_conversation_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='topics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
