# Generated by Django 4.0 on 2021-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_conversation_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='actions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
